apiVersion: v1
kind: ConfigMap
metadata:
  name: product-api-config
  namespace: devops-l3gl
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/inventorydb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: ""
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SERVER_PORT: "8086"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api
  namespace: devops-l3gl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-api
  template:
    metadata:
      labels:
        app: product-api
    spec:
      containers:
        - name: product-api
          image: sokhna54/product-api:latest
          ports:
            - containerPort: 8086
          envFrom:
            - configMapRef:
                name: product-api-config
          resources:
            requests:
              memory: "250Mi"
              cpu: "200m"
            limits:
              memory: "500Mi"
              cpu: "400m"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8086
            initialDelaySeconds: 180
            periodSeconds: 20
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8086
            initialDelaySeconds: 210
            periodSeconds: 30
            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: product-api
  namespace: devops-l3gl
spec:
  selector:
    app: product-api
  ports:
    - port: 8086
      targetPort: 8086
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: product-api-ingress
  namespace: devops-l3gl
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: product-api
                port:
                  number: 8086